USE YOUTUBE

SELECT TOP (1000) [category]
      ,[product]
  FROM [YOUTUBE].[dbo].[products]

    SELECT CATEGORY, 
		 COUNT(CATEGORY) OVER() AS COUNTS,
		 CUME_DIST() OVER(ORDER BY PRODUCT)
  FROM products


  SELECT CATEGORY, COUNT(CATEGORY)
  FROM products
  GROUP BY category
  ORDER BY COUNT(CATEGORY)

  SELECT *,CATEGORY, 
		 COUNT(CATEGORY) OVER() AS COUNTS,
		 CUME_DIST() OVER(ORDER BY PRODUCT) AS CUMULATICE_DIST,
		 RANK() OVER(ORDER BY PRODUCT) AS RNK
  FROM products

