use YOUTUBE
SELECT * FROM AIRBNB

SELECT NEIGHBOURHOOD_GROUP, COUNT(number_of_reviews) AS COUNT_OF_REVIEWS
FROM AIRBNB
GROUP BY NEIGHBOURHOOD_GROUP
ORDER BY COUNT_OF_REVIEWS DESC


--FIND OUT THE DA OF WEEK WITH HIGHEST AMOUNT OF SALES
SELECT * FROM SALESDATA

SELECT 
	DATENAME(WEEKDAY, PURCHASEDATE) AS DAYS,
	SUM(AMOUNT) AS TOTAL_AMOUNT

FROM SALESDATA
GROUP BY DATENAME(WEEKDAY, PURCHASEDATE)
ORDER BY TOTAL_AMOUNT DESC

CREATE TABLE P